### PR TITLE
WIP: Added Windows and Notes support

### PR DESCRIPTION
**Pull request by mxmauro**
Hi @zeldovich ,

This refactory adds full support for Windows (any version) and notes up-to 768 bytes (because the lack of memory)

Feel free to check it.

Kind regards,
Mauro.

### CODE REVIEW

**Comment by zeldovich** [comment]
Can you say more about what's going on here?

It seems like there's a bunch of changes here, some seemingly related to building with a different C compiler (on Windows?), some related to changing the UI logic, etc.

Does Ledger have a standard process for building Ledger apps on Windows?  What compiler are you supporting with these changes?

If you could break this up into individual changes that address specific concerns, it'd be easier for me to make sense of them, to give feedback and/or merge them.

**Comment by mxmauro** [comment]
The build is always on Linux (Ledger SDK only runs on Linux)

One of the changes is how the private key is built. Now using `os_perso_derive_node_bip32_seed_key` because the other function is not fully supported on Nano S, only on Blue.

That was the main reason that makes Ledger to crash on Windows when it calls to `cx_eddsa_sign`.

Most of the code is a refactory to use the UX flow seen in Ledger apps like BTC and ETH wallets. I removed the cycling `lineBuffer`.

Also separated many functions in different files/subfunctions by their tasks. (UI and the flow for APDU requests).

Removed `INS_SIGN_PAYMENT_V2` and `INS_SIGN_KEYREG_V2`. All calls must follow the APDU format.

Added support for notes. When a sign request is sent to Ledger, `P1` indicates if it is the end of the stream. First packet has the same format you used for a tx and the following are treatened as a stream of bytes that builds the note field.

TO-DO: I'll change the PR name to WIP. Currently the tx approval just asks for confirmation. It is a bit annoying to confirm all the steps and I wanted to ask you if you really want it.

**Comment by zeldovich** [comment]
> One of the changes is how the private key is built. Now using `os_perso_derive_node_bip32_seed_key` because the other function is not fully supported on Nano S, only on Blue.

Can you say more about this?  I don't think I've ever seen `os_perso_derive_node_bip32` fail in my use of the app, and I'm using only the Nano S (not the Blue).

> That was the main reason that makes Ledger to crash on Windows when it calls to `cx_eddsa_sign`.

I see, so you were running into some case where `os_perso_derive_node_bip32` was failing, and this caused `cx_eddsa_sign` to crash?  Do you know why Windows is relevant to `os_perso_derive_node_bip32` failing?

> Most of the code is a refactory to use the UX flow seen in Ledger apps like BTC and ETH wallets. I removed the cycling `lineBuffer`.
> 
> Also separated many functions in different files/subfunctions by their tasks. (UI and the flow for APDU requests).

It'd be helpful to review and merge that separately.

> Removed `INS_SIGN_PAYMENT_V2` and `INS_SIGN_KEYREG_V2`. All calls must follow the APDU format.

Why?  We might still have old Algorand node software that talks to the Ledger using the `_V2` calls.

> Added support for notes. When a sign request is sent to Ledger, `P1` indicates if it is the end of the stream. First packet has the same format you used for a tx and the following are treatened as a stream of bytes that builds the note field.

Yeah, it'd be nice to support note fields.  Thanks for this!

> TO-DO: I'll change the PR name to WIP. Currently the tx approval just asks for confirmation. It is a bit annoying to confirm all the steps and I wanted to ask you if you really want it.

I'm not sure I understand what you're saying here.  Are you proposing to display fewer fields before asking the user to approve?

**Comment by mxmauro** [comment]
> Can you say more about this? I don't think I've ever seen `os_perso_derive_node_bip32` fail in my use of the app, and I'm using only the Nano S (not the Blue).

To be honest I don't know why the problem happens. You know, Ledger documentation sucks and I based the changes on what I saw in ETH, BTC, Stellar and some other apps.

> I see, so you were running into some case where `os_perso_derive_node_bip32` was failing, and this caused `cx_eddsa_sign` to crash? Do you know why Windows is relevant to `os_perso_derive_node_bip32` failing?

From my point of view, seems `os_perso_derive_node_bip32` does not initialize the whole struct properly causing `cx_eddsa_sign` to crash (after some time Ledger self restarts)

Why it happens on Windows and not on Linux, I have no idea. But as I said above, I did the changes based on what I saw on other projects where `os_perso_derive_node_bip32` was used only in Ledger Blue.

> > Most of the code is a refactory to use the UX flow seen in Ledger apps like BTC and ETH wallets. I removed the cycling `lineBuffer`.
> > Also separated many functions in different files/subfunctions by their tasks. (UI and the flow for APDU requests).
> 
> It'd be helpful to review and merge that separately.

I'll try. I was modifying all until I found the real issue. Despite the bunch of changes, the code is easy to follow and some of them (like the try/try/catch/catch etc) were copied from their btc/eth apps (apache license)
 
> > Removed `INS_SIGN_PAYMENT_V2` and `INS_SIGN_KEYREG_V2`. All calls must follow the APDU format.
> 
> Why? We might still have old Algorand node software that talks to the Ledger using the `_V2` calls.

I think it would be better to make this breaking change now because the use of Ledger in Algorand is not widespread and avoid communication issues in the future.

> > Added support for notes. When a sign request is sent to Ledger, `P1` indicates if it is the end of the stream. First packet has the same format you used for a tx and the following are treatened as a stream of bytes that builds the note field.
> 
> Yeah, it'd be nice to support note fields. Thanks for this!

You are welcome.

> > TO-DO: I'll change the PR name to WIP. Currently the tx approval just asks for confirmation. It is a bit annoying to confirm all the steps and I wanted to ask you if you really want it.
> 
> I'm not sure I understand what you're saying here. Are you proposing to display fewer fields before asking the user to approve?

Yes, or we can shorten the addresses display to `AAA...BBBB` format.

It is like when people install an application.... clicks next next next without reading anything (including agreements hahaha). We may show receiver address in the compressed format, amount and fees and then confirm for e.g.

**Comment by zeldovich** [comment]
> > I'm not sure I understand what you're saying here. Are you proposing to display fewer fields before asking the user to approve?
> 
> Yes, or we can shorten the addresses display to `AAA...BBBB` format.
> 
> It is like when people install an application.... clicks next next next without reading anything (including agreements hahaha). We may show receiver address in the compressed format, amount and fees and then confirm for e.g.

It's pretty easy for an adversary to generate their own private key (and corresponding address) that matches the victim's intended address on the first and last few characters, if we only display those.

**Comment by mxmauro** [comment]
What do you prefer? Full target address plus amount plus fee, sounds good for you?

**Comment by zeldovich** [comment]
> > Can you say more about this? I don't think I've ever seen `os_perso_derive_node_bip32` fail in my use of the app, and I'm using only the Nano S (not the Blue).
> 
> To be honest I don't know why the problem happens. You know, Ledger documentation sucks and I based the changes on what I saw in ETH, BTC, Stellar and some other apps.
> 
> > I see, so you were running into some case where `os_perso_derive_node_bip32` was failing, and this caused `cx_eddsa_sign` to crash? Do you know why Windows is relevant to `os_perso_derive_node_bip32` failing?
> 
> From my point of view, seems `os_perso_derive_node_bip32` does not initialize the whole struct properly causing `cx_eddsa_sign` to crash (after some time Ledger self restarts)
> 
> Why it happens on Windows and not on Linux, I have no idea. But as I said above, I did the changes based on what I saw on other projects where `os_perso_derive_node_bip32` was used only in Ledger Blue.

I don't see any calls to `os_perso_derive_node_bip32_seed_key` in either the Ethereum or BTC Ledger apps.  As far as I can tell, both of them call `os_perso_derive_node_bip32`, same as the Algorand app does right now.  The Stellar app uses `os_perso_derive_node_bip32_seed_key` as you describe.

I ported Stellar's use of `os_perso_derive_node_bip32_seed_key`; does the new code avoid the bug for you?  Still quite puzzling what's going on, especially given that Ethereum and BTC apps use the `os_perso_derive_node_bip32` API.

**Comment by zeldovich** [comment]
> What do you prefer? Full target address plus amount plus fee, sounds good for you?

I'm thinking about it from the other direction: what fields are you proposing to omit?  It sounds like you want to omit validity rounds, genesis ID and hash, sender address, tx type?

I'd be OK with omitting genesis hash if the hash matches a hard-coded value for mainnet (and the genesis ID value is "mainnet-v1.0").

Validity rounds seem important so that you don't sign transactions into the future.

Omitting sender seems OK if it matches the Ledger device public key.

**Comment by mxmauro** [comment]
> > What do you prefer? Full target address plus amount plus fee, sounds good for you?
> 
> I'm thinking about it from the other direction: what fields are you proposing to omit? It sounds like you want to omit validity rounds, genesis ID and hash, sender address, tx type?

For payment tx, only show target, amount and fees. For others, like the future assets, it will display data according.

> I'd be OK with omitting genesis hash if the hash matches a hard-coded value for mainnet (and the genesis ID value is "mainnet-v1.0").

Sounds good for me. Same applies to the from field must match the stored key in the device.

> Validity rounds seem important so that you don't sign transactions into the future.

But delayed/programmable transactions is a good feature for wallets managers.

**Comment by zeldovich** [comment]
I spent a while tracking down why `os_perso_derive_node_bip32_seed_key` still fails.  As far as I can tell, it fails when called with a bip32 path length of 5 (which we use), but does not fail when called with a bip32 path length of 3 (which is what the Stellar app uses).  To preserve existing user keys, we should stick with the original bip32 paths.

If you have a way of reproducing the Windows issue, I can try debugging that separately, but for the time being, I rolled back to calling `os_perso_derive_node_bip32` as before.

**Comment by mxmauro** [comment]
I succeeded to call it if I or all the 5 bip32 `uint32_t` values are or'ed `0x80000000`

**Pull request closed without merging**
