### PR TITLE
Add AlgoGems, Yieldly, Smile Coin, Opulous, Exodus, Choice Coin, goBTC, goETH & goMINT

### PR DESCRIPTION
**Pull request by salvatorecorvaglia**

### CODE REVIEW

**Comment by ag14774** [comment]
Is it just me or does the development of this seems a bit dead in general?

**Comment by ag14774** [comment]
@salvatorecorvaglia The team at Ledger might be more active. They have a fork: https://github.com/LedgerHQ/app-algorand

**Comment by salvatorecorvaglia** [comment]
@ag14774 no, that's the Ledger repository, you need to update this first and then postpone the changes there.

**Comment by ainhoa-a** [comment]
This has been implemented and it is part of the most recent Algorand Ledger app release, version 2.1.7

**Comment by ftheirs** [comment]
This asset is supported on latest release [v2.1.9](https://github.com/LedgerHQ/app-algorand/releases/tag/v2.1.9):
https://github.com/LedgerHQ/app-algorand/blob/56c42a91c7113ee4be38d17f425d8ad783fc7a75/app/src/algo_asa.c#L43-L51

This issue can be closed! 🚀

**Pull request closed without merging**
