### PR TITLE
Update algo_asa.c

### PR DESCRIPTION
**Pull request by Dumuzi-LTBX**
Add Loot Box ASA

### CODE REVIEW

**Comment by ftheirs** [comment]
This asset is supported on latest release [v2.1.9](https://github.com/LedgerHQ/app-algorand/releases/tag/v2.1.9):
https://github.com/LedgerHQ/app-algorand/blob/56c42a91c7113ee4be38d17f425d8ad783fc7a75/app/src/algo_asa.c#L41

This issue can be closed! 🚀

**Comment by Dumuzi-LTBX** [comment]
I do not see those changes reflected live. I'm unable to add/view my asset
as an option to be added. I did update the ledger software and firmware.

**Comment by ainhoa-a** [comment]
What wallet are you using? In the Ledger App is enabled

**Comment by Dumuzi-LTBX** [comment]
Ledger app.  The list of ASAs to add to algorand account have not been
updated. LTBX others from the list are not on there.  Still same list as
before. Ledger hardware and software is up to date. I can provide more info
if needed.

**Comment by ftheirs** [comment]
Hey @Dumuzi-LTBX, you are right! In LedgerLive the list is not updated but that is out of the scope from the app. You can try with [MyAlgo wallet](https://wallet.myalgo.com/) that it has I think all assets

WhatsApp Image 2023-10-18 at 12 14 01

**Comment by Dumuzi-LTBX** [comment]
I never had issues viewing my asset anywhere else except ledger live. How
does one go to get that updated? Ledger support is not sure what to do. I
was under the impression that this was the way to update it.

Thanks!

**Pull request closed without merging**
